spring:
  application:
    name: CONFIG-DEFAULT
eureka:
  instance:
    prefer-ip-address: true    
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #With docker config use host.docker.internal as localhost is not accessible due to host os not being used
      defaultZone: http://host.docker.internal:8761/eureka/
      #default-zone: http://localhost:8761/eureka/

